### ISSUE TITLE
Cannot return a reference to the RMatrix inside an HMatrix

### ISSUE THREAD

**Issue by captain-yoshi** [BurksEngineering/TcTransform#1]
I am trying to return a reference to the rotation of a homogenous matrix to avoid a copy.

I have a method from a function block :
```cpp
// Method of a FB
METHOD getRotationMatrix: REFERENCE TO RMatrix
VAR_INPUT
END_VAR
---
getRotationMatrix REF= HmMember.RMatrixComponent;
```
And the main program :
```cpp
// MAIN
PROGRAM MAIN
VAR
        robot : RobotFB;
	Rm : REFERENCE TO RMatrix;
END_VAR
---
robot();
Rm REF= robot.getRotationMatrix();
```
This compiles fine, but when I try to run this I get the Blue Screen of Death from Windows ! I know this scheme works with a Matrix object. Could it be that it is because the Ref is from the _RMatrixComponent_ instead of _RMatrix_ ?

**Comment by BurksEngineering** [comment]
The RMatrixComponent Property Getter returns a value, not a reference. I think under the hood the compiler has to create a local variable inside your method, which lives in stack memory, in order to store the value. Once the method returns, the stack memory location is no longer valid but you are still holding on to a (now invalid) pointer to it. My guess is that is why you get a blue screen :(

If you are trying to avoid a bunch of excessive memory copying, note that the RMatrixComponent property is performing a memory copy into the function return value anyway. So, in the example code here, if you reorganized things to send *in* references to existing variables from outside of your method (which you want to be filled with new RMatrix data) then the internal HMatrix memcopy won't be wasted (kind of like an 'outval' param in some languages).

As a different approach, If you want to simultaneously interact with an H matrix and an R matrix, all from the same data, then I suggest using the '[Matrix Accessor](https://github.com/BurksEngineering/TcMatrix#matrix-accessors)' functionality (which is what is going on under the hood anyway - it just fakes out the indexing of the 4x4 matrix to feel like a 3x3 matrix). You could even make a derived RMatrix class and override the 'GetI' and 'SetI' methods to interact with an HMatrix just like the Matrix Accessor!

Hit me up on [linkedin ](www.linkedin.com/in/andrew-l-burks)if you want to chat about the specifics of your project - maybe I can help find a good approach?

**Comment by captain-yoshi** [comment]
Thank you for your detailed answer.

The Matrix Accessors are really powerful ! Exactly what I needed. Will have a second look at the documentation now that I'm more used to the API.

> Hit me up on [linkedin ](https://github.com/BurksEngineering/TcTransform/issues/www.linkedin.com/in/andrew-l-burks)if you want to chat about the specifics of your project - maybe I can help find a good approach?

Will have a talk with my Boss to see if I'm allowed to share details about the project. Will keep you updated.

**Comment by captain-yoshi** [comment]
@BurksEngineering

Can I pass a 3x1 **_SubMatrixAccessor_** (from an _HMatrix_) to a function needing a **_Vector3_** ? It works if the input is of type _Matrix_.

It gives me this error : Type 'SubMatrixAccessor' is not equal to type 'Vector3' of VAR_IN_OUT 'JO'

**Comment by BurksEngineering** [comment]
Nope. The strict type checking makes sure that matricies passed in are the right size. The two ways I can think of to get around this are:
1. You can probably make a derived class of the Vector3 FB and use a matrix accessor for memory addressing instead of the internal static array (just need to override GetI() and SetI() ).
2. If you are familiar with the math required for transformations, you can just do the math with SubMatrixAccessor and TcMatrix directly, but that kind of defeats the point.

If you are truly hanging on to the Vector3 outside of the context of the HMatrix, then you should probably just make a copy (every cycle).
