### ISSUE TITLE
Should the CrossProduct of 2 parallel vectors return [0, ..., 0]

### ISSUE THREAD

**Issue by captain-yoshi** [BurksEngineering/TcTransform#2]
I have a recursive function that does multiple cross products, and sometimes the vectors are parallel. In this case, the function `Vector_CrossProduct`  sets the [vector result](https://github.com/BurksEngineering/TcMatrix/blob/main/TcMatrix/TcMatrix/POUs/Functions/Vector/Vector_CrossProduct.TcPOU#L59-L63) untouched. If the supplied result vector is not initialized to zero, then the result is erroneous. I would have thought that the result would be filled with zeroes.

```bash
VAR
	V1 : Vector3;
	V2 : Vector3;
	V3 : Vector3;
END_VAR
---

// Initialize cross product result with values different from 0
V3.SetFromComponents(1,1,1); 

// Make the 2 vectors parallel
V1.SetFromComponents(0,0,1);
V2.SetFromComponents(0,0,1);

// Compute the cross product
V3.SetAsCrossProduct(V1, V2);

// Gives
//     V3 = [1, 1, 1]
// But should be 
//     V3 = [0, 0, 0]
```

I can initialize my vector with zeros, but I think the better approach would be to set to zero in the `Vector_CrossProduct`. Moreover, the `SetAsCrossProduct `and `GetVector3CrossProduct `methods of the Vector3 class does not return the error...

**Comment by BurksEngineering** [comment]
Thanks for bringing this up. It is tricky to try and package functions that might not have a valid return (like matrix product, cross product, inverse, etc) into convenient 'easy' functions for higher level libraries. There are a few things I have been thinking about after reading your comment and reviewing the code:

Is adding a general purpose 'NaN' state to all matrix objects, similar to REAL, a good idea? The benefit is obviously that functions don't need to return a boolean true/false. The downside is that the user has to check if Matrix.IsNan() constantly. This is probably not the way to go.

Not including the boolean result from the internal Vector_CrossProduct() function into the SetAsCrossProduct() result is a huge oversight, but there isn't a good way to pass it through the similar GetVector3CrossProduct() function anyway (I hate OUT_VARs). I normally don't think that setting result values to zero should indicate failure (zero is often a valid state) but in the special case of cross products a [0,0,0] vector is certainly an impossible result! Should the general purpose function for cross products be returning the [0,0,0] vector, but NOT an error, in the case of parallel inputs?

Independently of the answer to the previous question, how would you feel about Vector3.SetAsCrossProduct() setting and Vector3.GetVector3CrossProduct() returning an empty Vector3 ([0,0,0]), but not using a BOOL to indicate success for either function, in order to maintain consistency within TcTransform? To help evaluate if the result of a cross product was valid or not, a helper function to the base matrix class could be added (IsEmpty()? IsCleared()?) to quickly check if every element of the matrix is zero.

Are there any other functions in TcTransform that have the potential to return an invalid result, but do not have a way to indicate the possibility? The matrix multiplication/transposition stuff should generally just work I think?

Thanks for your help, and let me know what you think of these ideas so I can implement the winners.

**Comment by captain-yoshi** [comment]
> Is adding a general purpose 'NaN' state to all matrix objects, similar to REAL, a good idea?

Like you said I don't think this is the way.

> Should the general purpose function for cross products be returning the [0,0,0] vector, but NOT an error, in the case of parallel inputs?

I think it should. [Matlab ](https://www.mathworks.com/help/matlab/ref/cross.html#bt9u2fz-5) returns a cross product of [0,0,0,]. Other libraries in robotics also return [0,0,0]. Generally they don't return an error unless the dimensions are not equal. But for the the Vector3 case, there should be no errors (maybe except for valid references).

> To help evaluate if the result of a cross product was valid or not, a helper function to the base matrix class could be added (IsEmpty()? IsCleared()?) to quickly check if every element of the matrix is zero.

I like this idea. In robotics we don't normally care about checking for the error, the vector of [0,0,0] will nullify the rest of the equation. In other domains, it may be important to check this behavior, thus having the IsEmpty() method would be important.

> Are there any other functions in TcTransform that have the potential to return an invalid result, but do not have a way to indicate the possibility? The matrix multiplication/transposition stuff should generally just work I think?

I don't think so, will have to check for that. Will let you know.

**Comment by BurksEngineering** [comment]
I added IsCleared property to TcMatrix, because IsEmpty property already exists and indicates if the matrix size is not greater than zero. I also added a test function FB_Vector3_test.WhenParallelCrossedExpectCleared to verify this behavior.
