### ISSUE TITLE
Cannot use the RMatrixComponent

### ISSUE THREAD

**Issue by captain-yoshi** [BurksEngineering/TcTransform#3]
It seems I can't do the following operation:
```bash
VAR_IN_OUT
    DK: HMatrix; // Direct kinematic
END_VAR
VAR
    DK_R : RMatrix;
END_VAR   

---

DK_R.CopyFrom(DK.RMatrixComponent);
// VAR_IN_OUT parameter 'M' of 'CopyFrom' needs variable with write access as input
```

TcMatrix: 1.4.2
TcTransform: 0.3.34

**Comment by BurksEngineering** [comment]
In the [documentation for VAR_IN_OUT CONSTANT](https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/2528771211.html) it is said that the "transfer of properties is not permitted". I wonder if function results are permitted? If so, I can probably just add an HMatrix.GetRMatrixComponent() helper function?

**Comment by captain-yoshi** [comment]
That would be awesome! The same should be done to the vector component.

**Comment by BurksEngineering** [comment]
I'm working on adding these simple getters, but I realized that in your specific use case you could be using simple assignment (" := ") to get the behavior you want:
`
DK_R := HMatrix.RMatrixComponent
`
My guess is that property getters work like ByRef out variables. This is enforced in the implementing code by requiring assignment (which is why property returns cannot be transferred directly into other functions). So when my internal property get code is interacting with 'RMatrixComponent' and writing values to it (from the internal matrixAccessor) it is actually operating directly on DK_R (or whatever the property is being assigned to).

**Comment by BurksEngineering** [comment]
It looks like this theory is further supported by the fact that property getters _can_ be used as VAR_IN function parameters (byVal) but _cannot_ be used in VAR_IN_OUT or VAR_IN_OUT CONSTANT (byRef) parameters. Unfortunately, the same is true for method return values so my proposed fix will not add anything.

The CopyFrom method is a weird case where there is no reason it should ever be implemented with a ByVal input, because that implies that assignment will copy the variable anyway. For base matrix functions ByRef is important to maintain compatability with DynamicMatrix, but all of the TcTransform specific stuff should be ByVal compatible. Are there any functions in TcTransform that you are finding do not allow for ByVal inputs using the RMatrixComponent or Vector3Component properties?
